### ISSUE TITLE
Review of proposals

### ISSUE THREAD

**Issue by bethanyriggle** [afsc-gap-products/GOA-Survey-Planning#57] opened 2022-10-27 21:36 UTC

**Comment by Ned-Laman-NOAA** [comment] 2023-02-27 17:59
Hi team. I'm starting my review of the special project requests today. Alex is or will shortly be in AMSEA cold water survival Trainer training so we might be a little delayed on this relative to the 1 March deadline in our Task List.

If there are questions or concerns about projects of the process let's share them here so we're all in the loop.

**Comment by Conrathcl** [comment] 2023-02-27 18:14
Thanks Ned,

Initial deadline for acceptance of proposals was March 3.  Both Liz and I have requested a one week extension this morning from Nancy.  I'll update here with that deadline.  

I put a meeting on the calendar for next week, but if we would rather tag-team emails I am good with that.  

I sent an email around about Bob M's proposal already - I'm not sure we have resolution on that one.  

I also think we need some more input on Susanne's project and how that will work out.  I will post the email chain here next. 

Alex started a google sheet that maybe we can share with Ned?

**Comment by Conrathcl** [comment] 2023-02-27 18:20
Email thread regarding the pcod tagging project.  I think I'm struggling with expectation/reality/change in culture on the vessel on this one. 

Hi Christina,
I am not quite sure what to say about this.  If we can identify spots to catch cod while at anchor then this would work fine.  Otherwise I would say we need to fish where we catch a a lot of cod.  The expectation is to release 20 tags during leg 2 and 3..  I will be on board for leg 3 and 4.  We mostly want to release the tags where we find  a lot of cod.  If we can identify some spots ahead of time and then anchor up there that might work.  Otherwise I am wondering if we can use days where we end a little early and then do ti?  We have not done this on the Gulf/Aleutian survey yet what the best way to do this would be.  If all goes well it should not take that long.  
As to 1:
we don't need to anchor for this, just drift or go very slow.  It should be done near a station where we found a lot of cod.
2.  Yes this is voluntary.  I however will identify and train several people from leg 2 so those will be the ones tagging the fish.  Fishing for them can by anyone.  
3.  We do not need a fishing liscense for this.  This is part of our scientific work.  However, if you have a fishing liscense you CAN fish for cod if you so choose.

Do you want to maybe talk about this in person?  I am happy to schedule a meeting...
Sus

On Mon, Feb 27, 2023 at 8:23 AM Christina Conrath - NOAA Federal <[christina.conrath@noaa.gov](mailto:christina.conrath@noaa.gov)> wrote:
Hi Susanne,

I think my concern with this project is that we are asking people to work during their down times and I was trying to get a better feel for what your expectation is for this project. 

So it is it safe to assume that:

1) This will not involve asking the vessels to anchor, but take advantage of times when the vessel is going to anchor.
2) This is a voluntary activity folks can do when they have the time/energy?.  Or would you prefer to set an expectation for the amount of work done or tags put out? 
3) Pre-identified individuals will be likely to fish anyway and provide their own fishing licenses?  

There are no wrong answers, I just need a little more information so we can evaluate your request and what we are asking of the survey team. 

Thanks!
Christina





On Fri, Feb 24, 2023 at 8:42 AM Susanne Mcdermott - NOAA Federal <[susanne.mcdermott@noaa.gov](mailto:susanne.mcdermott@noaa.gov)> wrote:
Hi Alex and Christina,
Yes I will train people for leg 2 and will be there on leg 3 and 4 for the PCOD tagging.
Susanne

On Wed, Feb 22, 2023 at 9:23 AM Alexandra Dowlin - NOAA Federal <[alexandra.dowlin@noaa.gov](mailto:alexandra.dowlin@noaa.gov)> wrote:
Good morning Liz,

Christina and I are reviewing special project requests for the 2023 Gulf of Alaska survey. 

We wanted to confirm that you have this project assigned to personnel that is trained in Pacific cod tagging. In the request, it is noted that Susanne will be leading the tagging. 
Let us know if this is still correct.

Thank you so much,
Alex

**Comment by Conrathcl** [comment] 2023-02-27 18:34
Apologies, if this is a lot at once.  Alex and I have been quietly picking away at this.  

Sponge reproduction project:

I also emailed Jon B. and Richard K. about the sponge reproduction study and the use of EMA.  I am waiting to hear back about the EMA which is a mix of ethanol, methanol, and glacial acetic acid.  If the vessels are in Seattle before the cruise begins there is the possibility to mix it up ahead of time (Jerry vounteered); if not the scientists will mix on board before leg 1. I did talk to Sean about this, he wasn't super concerned about the chemical mix, but it sounds like it is extra work for the RSST crew wrt to shipping, etc. I'll let you know what I hear back from them.

**Comment by Ned-Laman-NOAA** [comment] 2023-02-27 18:42
Given the current status and everyone's time commitments, I agree with asking for the extension. It's great to see that you and Alex have already been tackling this. I'm late to the party!

As pertains to a different thread about populating sampling rubrics on Specimen Tablets by 3/10, special collection requests that require Specimen Tablet data entry (e.g., formal length-weight requests, maybe Susanne's tagging study [haven't read it yet]) are the focus of that deadline. Thus, if you're aware that there are/aren't any special requests that require Specimen Tablet data entry, we can prioritize or ignore as appropriate relative to that 3/10 deadline.

As for Susanne's project, since it doesn't come with additional time added, I'd expect these collections to be opportunistic and after the main work day is completed. I'll probably have more to say on this one after I've read through the projects. 

RE the sponge collection. Alaska Provider is no longer planning to come back to Seattle before our field season. Ocean Explorer currently is planning to be back. Sean is scheduled on the Provider Legs 1 and 2 so can mix his chemicals in DH if it comes to that.

**Comment by Conrathcl** [comment] 2023-03-01 16:23
Hi Ned,

Alex emailed him to see if a regular chest freezer was acceptable for preserving his specimens.  He confirmed that a regular chest freezer would work.  

Apologies for not keeping you in the loop.  I will share Alex's spreadsheet that has our notes and actions.

**Comment by Conrathcl** [comment] 2023-03-01 16:29
Spreadsheet that Alex created is[ here](https://docs.google.com/spreadsheets/d/1BXkY1IZEQPrjjRxSBjikKYx4NVHLga1NsKagrqNib4Q/edit?usp=sharing).  This has our notes and action items, Jerry's notes, the priority rankings, and all the details of each project.

**Comment by Conrathcl** [comment] 2023-03-01 16:56
Possible topic for next week's meeting.  I was thinking about if/how we might incorporate some of the genetic-types of projects (POP, northern, p-cod, and w. pollock) in with the otolith collections and possibly not have to take data on pencil and paper, but put those data into the specimen tablets.  I chatted with Heather about this and one possibility is to put the genetic specimen number in the tablet as a note attached to the otolith data. I think this might  work well for the gadid collections but I'm less certain of the rockfish ones as we may need to take additional samples beyond what we are collecting for otoliths based on [the map Wes sent](https://drive.google.com/file/d/18j81mIKel1-_4I4vDu6rQnYl08SJIu8S/view?usp=share_link).  I'll dive into the details of the projects before we meet to see if this might be doable. Another option is to add a specimen collection separate from the otolith collection, but since these are all otolith species and we may want to combine sampling that could get messy... Also, if we want to do a separate specimen collection we need to decide that soon, otherwise most of this discussion can probably wait a bit.

**Comment by Conrathcl** [comment] 2023-03-09 17:30
Hi Ned and Alex,
I just wanted a quick follow up to our meeting.  Nancy is going to want to know what projects we are accepting/rejecting on Friday.  I sent an email to Bob this morning and one to the safety folks about the EMF project.  I think we are going to accept or provisionally accept all projects but I wanted to check and see if we needed to chat about anything before that.  There is still time to tinker with the projects a bit and reach out to authors but if there is anything we think we might want to reject or if you have any significant concerns that we missed, we should chat about it sooner rather than later.
Thanks, Christina

**Comment by Ned-Laman-NOAA** [comment] 2023-03-09 17:36
I'm transferring my recent email to you both to our repo here so it's saved for posterity (see below). I agree that we're provisionally accepting all projects. What do you think about emphasizing to specific requesters who's projects we've identified as having potential conflicts with other priorities that the ultimate responsibility for prosecuting special request resides with the FPC in consultation with the Special Project Lead and Program Leader. Basically re-emphasizing that acceptance is no guarantee of completion.

Based on our conversation yesterday, there were only a few additional concerns I had from my review that we didn't specifically address "out loud" so I'll bring them to your attention here. You've probably already considered these and begun addressing them, but just in case not, here's what I've got.

The JPA isotopes project requires a -20C freezer. The requester would need to provide this freezer.

The assignment of the whole crab collection for Observers will need to be mindful of freezer space which is pretty limited on OEX and pretty bountiful on the AKP. If we assign this project to both boats, have DLs be mindful on the OEX that they could transfer frozen collections to the AKP at in ports if they're running out of freezer space.

Echoing some of the Christina's concerns about genetics projects, I remain concerned about the bottleneck that's going to be created by collecting genetic tissues and otoliths for POP and other RFs. This has burned us in the past so I think we need to set appropriate expectations for the requesters ahead of time and empower our DLs and FPCs to curb collections in the field that are impacting our station progress.

**Comment by Conrathcl** [comment] 2023-03-09 20:39
Just to hopefully put the freezer issue to bed.  This is the email from PI of the isotope project.  

Hi Alex - 

Thanks for writing.  A standard chest freezer will be fine.  Also, opportunistic sampling is ok as well.  I am just hoping to get a decent range of fish sizes and samples that are reasonably distributed across the survey grid to the extent that is possible.  

I didn't want to be too prescriptive - I hoped to make it  more flexible to make it easier on the crew.  But I also hope to avoid having big chunks of samples come from the same station.  If that's possible I would appreciate it - but at the end of the day I am happy to get whatever works best within the confines of everything else you all have to do during the survey.

Thanks and let me know if you have any other questions.

**Comment by AlexandraDowlin-NOAA** [comment] 2023-03-15 22:12
Notes from 3/15/2023 (Christina, Ned, Alex)

- Start requests earlier (Nov/dec), close in jan.
- Clarify roles (project reviewers: Ned, Christina, Alex, Jerry, Nancy, Joanna)
- Build charter about how this group will work, establish clear process
- Review bottle neck/overlap of projects
- Lead of projects contacts SECO

**Comment by AlexandraDowlin-NOAA** [comment] 2023-03-16 17:48
@Ned-Laman-NOAA begin discussion with Stan and Nancy about opening special project requests early (November/December) and closing in January. Giving more time for discussion/acceptance/questions.

**Closed** 2023-08-17 21:09 UTC
Labels: Special Projects
